export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const ORDER_SENT = 'ORDER_SENT';
export const ORDER_CHANGED = 'ORDER_CHANGED';
export const ORDER_CANCELLED = 'ORDER_CANCELLED';
export const ORDER_ACCEPTED_BY_CUSTOMER = 'ORDER_ACCEPTED_BY_CUSTOMER' ;
export const ORDER_ACCEPTED_BY_SUPPLIER = 'ORDER_ACCEPTED_BY_SUPPLIER' ;
export const ORDER_ACCEPTED_WITH_RESPONSE = 'ORDER_ACCEPTED_WITH_RESPONSE' ;
export const GET_SENT_ORDERS = 'GET_SENT_ORDERS';
export const GET_RECEIVED_ORDERS = 'GET_RECEIVED_ORDERS';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const ORDER_RETRIEVED = 'ORDER_RETRIEVED';
export const ORDER_REJECTED = 'ORDER_REJECTED' ;
export const ORDER_ADDED_TO= 'ORDER_ADDED_TO' ;
export const GET_DOC_FOR_ORDER_NEGOTIATION = 'GET_DOC_FOR_ORDER_NEGOTIATION';
export const GET_DOC_FOR_ORDER_CHANGE = 'GET_DOC_FOR_ORDER_CHANGE';

export const GET_PRODUCTS = "GET_PRODUCTS"; 
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';

export const GET_PARTIES = 'GET_PARTIES';   
export const GET_OTHER_PARTIES = 'GET_OTHER_PARTIES';  
export const PARTY_DELETED= 'PARTY_DELETED';
export const PARTY_ADDED = 'PARTY_ADDED';
export const PARTY_UPDATED = 'PARTY_UPDATED'; 
export const PARTY_RETRIEVED = 'PARTY_RETRIEVED';

export const GET_SETTINGS = 'GET_SETTINGS'; 